### ISSUE TITLE
Unbound Local Error, Name Error on 'box_file_path'

### ISSUE THREAD

**Issue by dsloan5** [jianlin-cheng/CryoTransformer#4]
Greetings,

I am new to coding and GitHub, please forgive if these are trivial errors.

I have begun using CryoTransformer.  After installing the requisite dependencies, running $ python3.9 predict.py  yields the following error.

```
$ Traceback (most recent call last):
$  File "/data/software/CryoTransformer/predict2.py", line 451, in <module>
$    infer(image_paths, model, postprocessors, device, output_dir)
$  File "/home/{user}/.local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
$    return func(*args, **kwargs)
$  File "/data/software/CryoTransformer/predict2.py", line 327, in infer
$    save_combined_star_file(box_file_path, prefix_file_name)
$UnboundLocalError: local variable 'box_file_path' referenced before assignment
```

I read on a webpage (https://stackoverflow.com/questions/9264763/why-does-this-unboundlocalerror-occur-closure) that Unbound Local Error might be fixed by including the 'global' keyword, which I added as follows at line 295 of predict.py:

```
294 $        # create directory for star files if not exist:
295 $        global box_file_path
296 $        box_file_path = output_dir + '/box_files/'
297 $        predicted_particles_visualizations_path = output_dir + '/predicted_particles_visualizations/'
298 $        if not os.path.exists(box_file_path):
299 $            os.makedirs(box_file_path)
```

But this gives a new error with a similar Traceback:

```
$ Traceback (most recent call last):
$  File "/data/software/CryoTransformer/predict2.py", line 451, in <module>
$    infer(image_paths, model, postprocessors, device, output_dir)
$  File "/home/{user}/.local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
$    return func(*args, **kwargs)
$  File "/data/software/CryoTransformer/predict2.py", line 327, in infer
$    save_combined_star_file(box_file_path, prefix_file_name)
$NameError: name 'box_file_path' is not defined
```

If anyone knows what is going on and is able to help, I would greatly appreciate it.  I may have other questions too as I attempt to train CryoTransformer on particle picks that I have already curated in CryoSparc and use it to predict a new set of particles.  If there is a better way to ask these and similar questions, please let me know.

Best,

**Comment by Ashwin-Dhakal** [comment]
Hi @dsloan5,  

I recommend reinstalling the environment and following the step-by-step guidelines in the README from the beginning. Based on your error snippet, it looks like you modified `predict.py` and ran `/data/software/CryoTransformer/predict2.py`. To ensure smooth execution, please avoid making changes to the existing codebase.

Based on the error messages, the issue is that `box_file_path` is not being properly defined before it's used in `save_combined_star_file()`. Adding `global` isn't the solution here since this isn't a case of modifying a global variable.  

It appears the code path where `box_file_path` is defined isn't being executed before line 327. To fix this:  

1. Move the directory path definitions outside the conditional block:
```python
def infer(...):
    # Define paths unconditionally
    box_file_path = os.path.join(output_dir, 'box_files')
    predicted_particles_visualizations_path = os.path.join(output_dir, 'predicted_particles_visualizations')
    
    # Create directories if needed
    os.makedirs(box_file_path, exist_ok=True)
    os.makedirs(predicted_particles_visualizations_path, exist_ok=True)
```

2. Use `os.path.join()` instead of string concatenation for paths.  
3. Use `exist_ok=True` to handle directory creation safely.  

Hope this helps!
